export const SOURCES = [
    { key: 'vidlink', sourceFile: 'vidlink', label: 'Sentinel', proxyParam: 'vl', timeout: 25000, jitter: 500, retries: 2, disabled: true },
    { key: 'vidzee', sourceFile: 'vidzee', label: 'Cipher', proxyParam: 'vz', timeout: 25000, jitter: 400, retries: 3, sourcesTimeout: 5000 },
    { key: 'meowtv', sourceFile: 'meowtv', label: 'Luminox', proxyParam: 'mt', timeout: 25000, jitter: 500, retries: 2, disabled: true },
    { key: 'flixhq', sourceFile: 'flixhq', label: 'Praetor', proxyParam: 'fq', timeout: 25000, jitter: 600, retries: 2, disabled: true },
    { key: 'cinesu', sourceFile: 'cinesu', label: 'Solaris', proxyParam: 'cs', timeout: 15000, jitter: 500, retries: 2, disabled: true },
    { key: 'icefy', sourceFile: 'icefy', label: 'Frostbyte', proxyParam: 'iy', timeout: 25000, jitter: 500, retries: 2, sourcesTimeout: 5000 },
    { key: 'momlover-nova', sourceFile: 'momlover', label: 'NovaStream', proxyParam: 'ns', timeout: 30000, jitter: 500, retries: 1, multiBase: true, bases: ['tulnex1'] },
    { key: 'momlover-vault', sourceFile: 'momlover', label: 'VaultFlix', proxyParam: 'vl', timeout: 30000, jitter: 600, retries: 1, multiBase: true, bases: ['moviebox'] },
    { key: 'momlover-wave', sourceFile: 'momlover', label: 'CineWave', proxyParam: 'cw', timeout: 30000, jitter: 700, retries: 1, multiBase: true, bases: ['fabric'] },
    { key: 'momlover-thorn', sourceFile: 'momlover', label: 'Thorn', proxyParam: 'th', timeout: 30000, jitter: 800, retries: 1, multiBase: true, bases: ['flax'] },
    { key: 'momlover-neo', sourceFile: 'momlover', label: 'NeoFlix', proxyParam: 'nf', timeout: 30000, jitter: 900, retries: 1, multiBase: true, bases: ['flix'] },
    { key: 'momlover-forge', sourceFile: 'momlover', label: 'ForgeCast', proxyParam: 'fg', timeout: 30000, jitter: 1000, retries: 1, multiBase: true, bases: ['ngflix'] },
    { key: 'aether', sourceFile: 'aether', label: 'Aether', proxyParam: 'ae', timeout: 25000, jitter: 500, retries: 2, sourcesTimeout: 5000 },
    { key: 'vidrock', sourceFile: 'vidrock', label: 'Obsidian', proxyParam: 'vr', timeout: 20000, jitter: 800, retries: 3, disabled: true },
    { key: 'vidsrc', sourceFile: 'vidsrc', label: 'Phantom', proxyParam: 'vs', timeout: 25000, jitter: 700, retries: 2, sourcesTimeout: 5000 },
    { key: 'vixsrc', sourceFile: 'vixsrc', label: 'Meridian', proxyParam: 'vx', timeout: 20000, jitter: 500, retries: 2, disabled: true },
    { key: 'videasy', sourceFile: 'videasy', label: 'Crystal', proxyParam: 'vy', timeout: 20000, jitter: 900, retries: 3, sourcesTimeout: 5000, disabled: true },
    { key: 'streammafia', sourceFile: 'streammafia', label: 'Syndicate', proxyParam: 'sm', timeout: 25000, jitter: 600, retries: 2, disabled: true },
    { key: '02movie', sourceFile: '02movie', label: 'Forge', proxyParam: 'zm', timeout: 35000, jitter: 600, retries: 1, disabled: true },
    { key: 'moviebox', sourceFile: 'moviebox', label: 'Vault', proxyParam: 'mb', timeout: 25000, jitter: 500, retries: 2, sourcesTimeout: 8000, disabled: true },
    { key: 'vidnest', sourceFile: 'vidnest', label: 'Haven', proxyParam: 'vn', timeout: 20000, jitter: 600, retries: 3, disabled: true },
    { key: 'popr', sourceFile: 'popr', label: 'Spark', proxyParam: 'pp', timeout: 20000, jitter: 600, retries: 2, disabled: true },
    { key: 'cinezo', sourceFile: 'cinezo', label: 'Relay', proxyParam: 'cz', timeout: 25000, jitter: 500, retries: 2, disabled: true },
    { key: 'vidfun', sourceFile: 'vidfun', label: 'Plasma', proxyParam: 'vf', timeout: 30000, jitter: 500, retries: 2, disabled: true },
    { key: 'fsharetv', sourceFile: 'fsharetv', label: 'Horizon', proxyParam: 'fs', timeout: 30000, jitter: 600, retries: 2, disabled: true },
    { key: 'vidapi', sourceFile: 'vidapi', label: 'Atlas', proxyParam: 'va', timeout: 25000, jitter: 500, retries: 2, disabled: true },
    { key: 'fsonic', sourceFile: 'fsonic', label: 'Thunder', proxyParam: 'fn', timeout: 35000, jitter: 600, retries: 1, disabled: true },
    { key: 'flaxmovies', sourceFile: 'flaxmovies', label: 'Vortex', proxyParam: 'fm', timeout: 15000, jitter: 500, retries: 2, disabled: true },
    { key: 'flixtrz', sourceFile: 'flixtrz', label: 'Radiant', proxyParam: 'fz', timeout: 25000, jitter: 600, retries: 2, disabled: true },
    { key: 'lookmovie', sourceFile: 'lookmovie', label: 'Vertex', proxyParam: 'lm', timeout: 30000, jitter: 700, retries: 2, disabled: true },
    { key: 'miruro', sourceFile: 'miruro', label: 'Quasar', proxyParam: 'mr', timeout: 25000, jitter: 500, retries: 2, disabled: true },
    { key: 'movsrc', sourceFile: 'movsrc', label: 'Surge', proxyParam: 'ms', timeout: 15000, jitter: 500, retries: 2, disabled: true },
    { key: 'peachify', sourceFile: 'peachify', label: 'Apex', proxyParam: 'pf', timeout: 25000, jitter: 600, retries: 2, disabled: true },
    { key: 'toustream', sourceFile: 'toustream', label: 'Torrent', proxyParam: 'ts', timeout: 25000, jitter: 700, retries: 2, disabled: true },
    { key: 'tryembed', sourceFile: 'tryembed', label: 'Pulse', proxyParam: 'te', timeout: 25000, jitter: 600, retries: 2, disabled: true },
    { key: 'vapor', sourceFile: 'vapor', label: 'Eclipse', proxyParam: 'vp', timeout: 15000, jitter: 500, retries: 2 },
    { key: 'vidify', sourceFile: 'vidify', label: 'Nova', proxyParam: 'vi', timeout: 20000, jitter: 700, retries: 2, disabled: true },
    { key: 'streamvault', sourceFile: 'streamvault', label: 'StreamVault', proxyParam: 'sv', timeout: 20000, jitter: 500, retries: 2, disabled: true },
    { key: 'movieboxonline', sourceFile: 'movieboxonline', label: 'MovieBox', proxyParam: 'mo', timeout: 15000, jitter: 500, retries: 2, disabled: true },
    { key: 'moviebite', sourceFile: 'moviebite', label: 'Orbit', proxyParam: 'bt', timeout: 25000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true, disabled: true },
    {
        key: 'animehub',
        sourceFile: 'animehub',
        label: 'Echo',
        proxyParam: 'ah',
        timeout: 25000,
        jitter: 500,
        retries: 2,
        objectArgs: true,
        disabled: true,
        cdnHeaders: [
            {
                pattern: /hlsx\d+cdn\.|burntburst\d+\.store|echovideo\.ru/i,
                headers: {
                    Referer: 'https://play2.echovideo.ru/',
                    Origin: 'https://play2.echovideo.ru',
                },
            },
        ],
    },
    { key: 'kiroku-sub', sourceFile: 'kiroku', label: 'Arcadia Sub', proxyParam: 'ks', timeout: 25000, jitter: 300, retries: 2, objectArgs: true, skipProxy: true, disabled: true },
    { key: 'kiroku-dub', sourceFile: 'kiroku', label: 'Arcadia Dub', proxyParam: 'kd', timeout: 25000, jitter: 300, retries: 2, objectArgs: true, skipProxy: true, disabled: true },
    { key: 'notorrent', sourceFile: 'notorrent', label: 'Nexus', proxyParam: 'nt', timeout: 25000, jitter: 600, retries: 2, disabled: true },
    { key: 'lordflix', sourceFile: 'lordflix', label: 'Crown', proxyParam: 'lf', timeout: 25000, jitter: 600, retries: 2 },
    { key: 'dahmermovies', sourceFile: 'dahmermovies', label: 'DahmerMovies', proxyParam: 'dm', timeout: 25000, jitter: 600, retries: 2, disabled: true },
    { key: '4khdhub', sourceFile: '4khdhub', label: '4KHDHub', proxyParam: '4k', timeout: 30000, jitter: 700, retries: 2, disabled: true },
];

export const SOURCE_MAP = Object.fromEntries(SOURCES.map(s => [s.key, s]));
export const ALLOWED_ORIGINS = ['*'];
export const HEALTH_PROBE_ID = '155';
export const CACHE_TTL = 5 * 60 * 1000;
