export const SOURCES = [
    // ─── CONFIRMED WORKING ──────────────────────────────────────────────────────
    { key: 'vidzee', sourceFile: 'vidzee', label: 'Cipher', proxyParam: 'vz', timeout: 25000, jitter: 400, retries: 3, objectArgs: true, skipProxy: true,},
    { key: 'icefy', sourceFile: 'icefy', label: 'Frostbyte', proxyParam: 'iy', timeout: 25000, jitter: 500, retries: 2, sourcesTimeout: 5000 },
    { key: 'notorrent', sourceFile: 'notorrent', label: 'Nexus', proxyParam: 'nt', timeout: 25000, jitter: 600, retries: 2,},
    { key: 'vidapi', sourceFile: 'vidapi', label: 'Atlas', proxyParam: 'va', timeout: 25000, jitter: 500, retries: 2 },
    // { key: 'streamguide', sourceFile: 'streamguide', label: 'StreamGuide', proxyParam: 'sg', timeout: 25000, jitter: 600, retries: 2, objectArgs: true, skipProxy: true,},
    { key: 'vidcore', sourceFile: 'vidcore', label: 'Onyx', proxyParam: 'vc', timeout: 25000, jitter: 600, retries: 2, objectArgs: true, skipProxy: true,},
    { key: 'vidfast', sourceFile: 'vidfast', label: 'Velocity', proxyParam: 'vt', timeout: 25000, jitter: 600, retries: 2, objectArgs: true, skipProxy: true,},
    { key: 'xpass', sourceFile: 'xpass', label: 'Spectra', proxyParam: 'xp', timeout: 25000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    { key: '1embed', sourceFile: '1embed', label: 'Zenith', proxyParam: '1e', timeout: 25000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    { key: 'mapple', sourceFile: 'mapple', label: 'Titan', proxyParam: 'mp', timeout: 25000, jitter: 600, retries: 2, objectArgs: true, skipProxy: true,},
    { key: 'opstream', sourceFile: 'opstream', label: 'Prism', proxyParam: 'op', timeout: 20000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    { key: 'vidbolt', sourceFile: 'vidbolt', label: 'Bolt', proxyParam: 'vb', timeout: 25000, jitter: 600, retries: 2, objectArgs: true, skipProxy: true,},
    { key: 'vidrift', sourceFile: 'vidrift', label: 'Rift', proxyParam: 'vd', timeout: 20000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    { key: 'vidup', sourceFile: 'vidup', label: 'Pinnacle', proxyParam: 'vu', timeout: 25000, jitter: 600, retries: 2, objectArgs: true, skipProxy: true,},

    // ─── NEW (from SDK) ─────────────────────────────────────────────────────────
    { key: 'rivestream', sourceFile: 'rivestream', label: 'Rive', proxyParam: 'rs', timeout: 25000, jitter: 500, retries: 2, objectArgs: true },
    { key: 'bcine', sourceFile: 'bcine', label: 'Bcine', proxyParam: 'bc', timeout: 25000, jitter: 500, retries: 2, objectArgs: true },
    { key: 'cinesrc', sourceFile: 'cinesrc', label: 'CineSrc', proxyParam: 'cr', timeout: 25000, jitter: 500, retries: 2, objectArgs: true },
    { key: 'frame', sourceFile: 'frame', label: 'Frame', proxyParam: 'fr', timeout: 25000, jitter: 500, retries: 2, objectArgs: true },
    { key: 'peestream', sourceFile: 'peestream', label: 'PeeStream', proxyParam: 'pe', timeout: 25000, jitter: 600, retries: 2, objectArgs: true },
    { key: 'pstream', sourceFile: 'pstream', label: 'FlyStream', proxyParam: 'pl', timeout: 25000, jitter: 500, retries: 2, objectArgs: true },
    { key: 'nova', sourceFile: 'nova', label: 'Nova', proxyParam: 'nv', timeout: 25000, jitter: 500, retries: 2, objectArgs: true },
    { key: 'vidvault', sourceFile: 'vidvault', label: 'VidVault', proxyParam: 'vv', timeout: 25000, jitter: 600, retries: 2, objectArgs: true },
    { key: 'lmscript', sourceFile: 'lmscript', label: 'LMScript', proxyParam: 'lx', timeout: 25000, jitter: 500, retries: 2, objectArgs: true },
    { key: 'luna-sub', sourceFile: 'luna', label: 'Luna Sub', proxyParam: 'lu', timeout: 25000, jitter: 500, retries: 2, objectArgs: true },
    { key: 'anihq', sourceFile: 'anihq', label: 'AniHQ', proxyParam: 'aq', timeout: 25000, jitter: 500, retries: 2, objectArgs: true },

    // ─── DISABLED (unconfirmed) ─────────────────────────────────────────────────
    // { key: 'vidlink', sourceFile: 'vidlink', label: 'Sentinel', proxyParam: 'vl', timeout: 25000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'meowtv', sourceFile: 'meowtv', label: 'Luminox', proxyParam: 'mt', timeout: 25000, jitter: 500, retries: 2,},
    // { key: 'flixhq', sourceFile: 'flixhq', label: 'Praetor', proxyParam: 'fq', timeout: 25000, jitter: 600, retries: 2,},
    // { key: 'cinesu', sourceFile: 'cinesu', label: 'Solaris', proxyParam: 'cs', timeout: 15000, jitter: 500, retries: 2,},
    // { key: 'momlover-nova', sourceFile: 'momlover', label: 'NovaStream', proxyParam: 'ns', timeout: 30000, jitter: 500, retries: 1, multiBase: true, bases: ['tulnex1'],},
    // { key: 'momlover-vault', sourceFile: 'momlover', label: 'VaultFlix', proxyParam: 'vl', timeout: 30000, jitter: 600, retries: 1, multiBase: true, bases: ['moviebox'] },
    // { key: 'momlover-wave', sourceFile: 'momlover', label: 'CineWave', proxyParam: 'cw', timeout: 30000, jitter: 700, retries: 1, multiBase: true, bases: ['fabric'] },
    // { key: 'momlover-thorn', sourceFile: 'momlover', label: 'Thorn', proxyParam: 'th', timeout: 30000, jitter: 800, retries: 1, multiBase: true, bases: ['flax'] },
    // { key: 'momlover-neo', sourceFile: 'momlover', label: 'NeoFlix', proxyParam: 'nf', timeout: 30000, jitter: 900, retries: 1, multiBase: true, bases: ['flix'] },
    // { key: 'momlover-forge', sourceFile: 'momlover', label: 'ForgeCast', proxyParam: 'fg', timeout: 30000, jitter: 1000, retries: 1, multiBase: true, bases: ['ngflix'] },
    // { key: 'aether', sourceFile: 'aether', label: 'Aether', proxyParam: 'ae', timeout: 25000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'vidrock', sourceFile: 'vidrock', label: 'Obsidian', proxyParam: 'vr', timeout: 20000, jitter: 800, retries: 3, objectArgs: true, skipProxy: true,},
    // { key: 'vidsrc', sourceFile: 'vidsrc', label: 'Phantom', proxyParam: 'vs', timeout: 25000, jitter: 700, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'vixsrc', sourceFile: 'vixsrc', label: 'Meridian', proxyParam: 'vx', timeout: 20000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'videasy', sourceFile: 'videasy', label: 'Crystal', proxyParam: 'vy', timeout: 20000, jitter: 900, retries: 3, objectArgs: true, skipProxy: true,},
    // { key: 'streammafia', sourceFile: 'streammafia', label: 'Syndicate', proxyParam: 'sm', timeout: 25000, jitter: 600, retries: 2,},
    // { key: '02movie', sourceFile: '02movie', label: 'Forge', proxyParam: 'zm', timeout: 35000, jitter: 600, retries: 1 },
    // { key: 'moviebox', sourceFile: 'moviebox', label: 'Vault', proxyParam: 'mb', timeout: 25000, jitter: 500, retries: 2, sourcesTimeout: 8000 },
    // { key: 'vidnest', sourceFile: 'vidnest', label: 'Haven', proxyParam: 'vn', timeout: 20000, jitter: 600, retries: 3, objectArgs: true, skipProxy: true,},
    // { key: 'popr', sourceFile: 'popr', label: 'Spark', proxyParam: 'pp', timeout: 20000, jitter: 600, retries: 2,},
    // { key: 'cinezo', sourceFile: 'cinezo', label: 'Relay', proxyParam: 'cz', timeout: 25000, jitter: 500, retries: 2,},
    // { key: 'vidfun', sourceFile: 'vidfun', label: 'Plasma', proxyParam: 'vf', timeout: 30000, jitter: 500, retries: 2,},
    // { key: 'fsharetv', sourceFile: 'fsharetv', label: 'Horizon', proxyParam: 'fs', timeout: 30000, jitter: 600, retries: 2 },
    // { key: 'fsonic', sourceFile: 'fsonic', label: 'Thunder', proxyParam: 'fn', timeout: 35000, jitter: 600, retries: 1 },
    // { key: 'flaxmovies', sourceFile: 'flaxmovies', label: 'Vortex', proxyParam: 'fm', timeout: 15000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'flixtrz', sourceFile: 'flixtrz', label: 'Radiant', proxyParam: 'fz', timeout: 25000, jitter: 600, retries: 2 },
    // { key: 'lookmovie', sourceFile: 'lookmovie', label: 'Vertex', proxyParam: 'lm', timeout: 30000, jitter: 700, retries: 2 },
    // { key: 'miruro', sourceFile: 'miruro', label: 'Quasar', proxyParam: 'mr', timeout: 25000, jitter: 500, retries: 2,},
    // { key: 'movsrc', sourceFile: 'movsrc', label: 'Surge', proxyParam: 'ms', timeout: 15000, jitter: 500, retries: 2,},
    // { key: 'peachify', sourceFile: 'peachify', label: 'Apex', proxyParam: 'pf', timeout: 25000, jitter: 600, retries: 2,},
    // { key: 'toustream', sourceFile: 'toustream', label: 'Torrent', proxyParam: 'ts', timeout: 25000, jitter: 700, retries: 2,},
    // { key: 'tryembed', sourceFile: 'tryembed', label: 'Pulse', proxyParam: 'te', timeout: 25000, jitter: 600, retries: 2,},
    // { key: 'vapor', sourceFile: 'vapor', label: 'Eclipse', proxyParam: 'vp', timeout: 15000, jitter: 500, retries: 2 },
    // { key: 'vidify', sourceFile: 'vidify', label: 'Nova', proxyParam: 'vi', timeout: 20000, jitter: 700, retries: 2,},
    // { key: 'streamvault', sourceFile: 'streamvault', label: 'StreamVault', proxyParam: 'sv', timeout: 20000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'movieboxonline', sourceFile: 'movieboxonline', label: 'MovieBox', proxyParam: 'mo', timeout: 15000, jitter: 500, retries: 2,},
    // { key: 'moviebite', sourceFile: 'moviebite', label: 'Orbit', proxyParam: 'bt', timeout: 25000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'animehub', sourceFile: 'animehub', label: 'Echo', proxyParam: 'ah', timeout: 25000, jitter: 500, retries: 2, objectArgs: true,},
    // { key: 'kiroku-sub', sourceFile: 'kiroku', label: 'Arcadia Sub', proxyParam: 'ks', timeout: 25000, jitter: 300, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'kiroku-dub', sourceFile: 'kiroku', label: 'Arcadia Dub', proxyParam: 'kd', timeout: 25000, jitter: 300, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'lordflix', sourceFile: 'lordflix', label: 'Crown', proxyParam: 'lf', timeout: 25000, jitter: 600, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'dahmermovies', sourceFile: 'dahmermovies', label: 'DahmerMovies', proxyParam: 'dm', timeout: 25000, jitter: 600, retries: 2,},
    // { key: '4khdhub', sourceFile: '4khdhub', label: '4KHDHub', proxyParam: '4k', timeout: 30000, jitter: 700, retries: 2,},
    // { key: '123anime', sourceFile: '123anime', label: 'Echo123', proxyParam: '1a', timeout: 25000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'anineko', sourceFile: 'anineko', label: 'Neko', proxyParam: 'an', timeout: 25000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'anipm', sourceFile: 'anipm', label: 'AniPM', proxyParam: 'ap', timeout: 25000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'biavox', sourceFile: 'biavox', label: 'Biavox', proxyParam: 'bv', timeout: 20000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'dulo', sourceFile: 'dulo', label: 'Dulo', proxyParam: 'dl', timeout: 25000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'fsonline', sourceFile: 'fsonline', label: 'FSOnline', proxyParam: 'fo', timeout: 25000, jitter: 600, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'goated', sourceFile: 'goated', label: 'Goated', proxyParam: 'go', timeout: 20000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'hexa', sourceFile: 'hexa', label: 'Hexa', proxyParam: 'hx', timeout: 20000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'kisskh', sourceFile: 'kisskh', label: 'KissKH', proxyParam: 'kk', timeout: 25000, jitter: 600, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'nekowatch', sourceFile: 'nekowatch', label: 'NekoWatch', proxyParam: 'nw', timeout: 25000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'netmirror', sourceFile: 'netmirror', label: 'NetMirror', proxyParam: 'nm', timeout: 30000, jitter: 700, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'purstream', sourceFile: 'purstream', label: 'PurStream', proxyParam: 'ps', timeout: 20000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'spencerdevs', sourceFile: 'spencerdevs', label: 'Spencer', proxyParam: 'sd', timeout: 25000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'vidsync', sourceFile: 'vidsync', label: 'VidSync', proxyParam: 'vy2', timeout: 25000, jitter: 600, retries: 2, objectArgs: true, skipProxy: true,},
    // { key: 'xyra', sourceFile: 'xyra', label: 'Xyra', proxyParam: 'xy', timeout: 20000, jitter: 500, retries: 2, objectArgs: true, skipProxy: true,},
];

export const SOURCE_MAP = Object.fromEntries(SOURCES.map(s => [s.key, s]));
export const ALLOWED_ORIGINS = ['*'];
export const HEALTH_PROBE_ID = '155';
export const CACHE_TTL = 5 * 60 * 1000;
